{"name": "Проверка работы формы регистрации", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_117.0.5938", "trace": "@allure.title(\"Проверка работы формы регистрации\")\n    def test_register_form():\n        practice_form = PracticeForm()\n>       practice_form.open()\n\ntest_mid-level-step-objects.py:9: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../model/practice_form.py:21: in open\n    browser.open('/automation-practice-form')\n../venv/lib/python3.10/site-packages/selene/support/shared/browser.py:78: in open\n    self.config.get_or_create_driver().get(url)\n../venv/lib/python3.10/site-packages/selene/support/shared/config.py:281: in get_or_create_driver\n    return self._source.get_or_create()\n../venv/lib/python3.10/site-packages/selene/support/shared/config.py:129: in get_or_create\n    return self.create()\n../venv/lib/python3.10/site-packages/selene/support/shared/config.py:110: in create\n    self._stored = self._set_driver()\n../venv/lib/python3.10/site-packages/selene/support/shared/config.py:192: in <lambda>\n    lambda: self._set_chrome_or_firefox_from_webdriver_manager()\n../venv/lib/python3.10/site-packages/selene/support/shared/config.py:259: in _set_chrome_or_firefox_from_webdriver_manager\n    return {'chrome': get_chrome, 'firefox': get_firefox}.get(\n../venv/lib/python3.10/site-packages/selene/support/shared/config.py:243: in get_chrome\n    ).install()\n../venv/lib/python3.10/site-packages/webdriver_manager/chrome.py:37: in install\n    driver_path = self._get_driver_path(self.driver)\n../venv/lib/python3.10/site-packages/webdriver_manager/core/manager.py:29: in _get_driver_path\n    binary_path = self.driver_cache.find_driver(driver)\n../venv/lib/python3.10/site-packages/webdriver_manager/core/driver_cache.py:95: in find_driver\n    driver_version = driver.get_version()\n../venv/lib/python3.10/site-packages/webdriver_manager/core/driver.py:42: in get_version\n    self.get_latest_release_version()\n../venv/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py:44: in get_latest_release_version\n    resp = self._http_client.get(url=latest_release_url)\n../venv/lib/python3.10/site-packages/webdriver_manager/core/http.py:33: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_117.0.5938\n\n../venv/lib/python3.10/site-packages/webdriver_manager/core/http.py:15: ValueError"}, "attachments": [{"name": "log", "source": "644150e4-c0cb-4cea-ae16-4b5fec6e847f-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "9570affc-ea94-4c58-8bd5-b97a8c6f72af-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "697643d1-3aa8-43af-a176-c86c60d20238-attachment.txt", "type": "text/plain"}], "start": 1698477561085, "stop": 1698477561937, "uuid": "4db4d5e7-be31-4bbf-8d92-a73a90575022", "historyId": "0c73e40bcc2acde743a21e6d249ac7cb", "testCaseId": "8b6516a4dd6ee56f13987bedd73cdfe2", "fullName": "tests.test_mid-level-step-objects#test_register_form", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_mid-level-step-objects"}, {"name": "host", "value": "elilap"}, {"name": "thread", "value": "58718-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_mid-level-step-objects"}]}